### ISSUE TITLE
VOXA as a library is too big

### ISSUE THREAD

**Issue by spatical** [VoxaAI/voxa#217]
The filesize of VOXA when included in another project has grown to be too large, currently when included in a project it is 19 MB.    Can we make it so the docs aren't included?  or how about the coverage folder?   

I last tried with   "voxa": "^3.1.0-alpha4",

 _/node_modules/voxa_
4.0K		LICENSE.md
4.0K		Makefile
4.0K		README.md
4.0K		_config.yml
**5.2M	coverage**
**3.6M	docs**
124K	hello-world
 32K	junit.xml
**2.1M	lib**
684K	node_modules
4.0K		package.json
4.0K		run-ci.sh
440K	src
512K	test
4.0K		tsconfig.json
4.0K		tslint.json
**5.9M	typedoc**
 80K	yarn.lock

**Comment by rmberrios** [comment]
Yes, we should include those files into .npmignore then make a new version of voxa

**Comment by omenocal** [comment]
This issue is solved now:

Voxa files' size has been reduced from
17.6 MB in 3.1.0-alpha7
to
1.9 MB in 3.1.0-alpha8

**Comment by omenocal** [comment]
npm 
npm 📦  voxa@3.1.0-alpha8
npm === Tarball Contents === 
npm 2.7kB  package.json                                                                               
npm 29B    _config.yml                                                                                
npm 218B   .editorconfig                                                                              
npm 6B     .ignore                                                                                    
npm 6B     .nvmrc                                                                                     
npm 205B   .nycrc                                                                                     
npm 1.1kB  LICENSE.md                                                                                 
npm 698B   Makefile                                                                                   
npm 2.6kB  README.md                                                                                  
npm 417B   tsconfig.json                                                                              
npm 451B   tslint.json                                                                                
npm 81.1kB yarn.lock                                                                                  
npm 509B   lib/src/azure.d.ts                                                                         
npm 1.8kB  lib/src/azure.js                                                                           
npm 706B   lib/src/azure.js.map                                                                       
npm 2.5kB  lib/src/directives.d.ts                                                                    
npm 4.1kB  lib/src/directives.js                                                                      
npm 3.9kB  lib/src/directives.js.map                                                                  
npm 192B   lib/src/errors/handler.d.ts                                                                
npm 1.7kB  lib/src/errors/handler.js                                                                  
npm 462B   lib/src/errors/handler.js.map                                                              
npm 1.1kB  lib/src/errors/index.d.ts                                                                  
npm 2.3kB  lib/src/errors/index.js                                                                    
npm 706B   lib/src/errors/index.js.map                                                                
npm 59B    lib/src/errors/NotImplementedError.d.ts                                                    
npm 219B   lib/src/errors/NotImplementedError.js                                                      
npm 188B   lib/src/errors/NotImplementedError.js.map                                                  
npm 122B   lib/src/errors/OnSessionEndedError.d.ts                                                    
npm 1.8kB  lib/src/errors/OnSessionEndedError.js                                                      
npm 493B   lib/src/errors/OnSessionEndedError.js.map                                                  
npm 115B   lib/src/errors/SSMLError.d.ts                                                              
npm 1.4kB  lib/src/errors/SSMLError.js                                                                
npm 289B   lib/src/errors/SSMLError.js.map                                                            
npm 52B    lib/src/errors/TimeoutError.d.ts                                                           
npm 191B   lib/src/errors/TimeoutError.js                                                             
npm 172B   lib/src/errors/TimeoutError.js.map                                                         
npm 3.1kB  lib/src/index.d.ts                                                                         
npm 6.9kB  lib/src/index.js                                                                           
npm 2.8kB  lib/src/index.js.map                                                                       
npm 308B   lib/src/lambda.d.ts                                                                        
npm 1.9kB  lib/src/lambda.js                                                                          
npm 693B   lib/src/lambda.js.map                                                                      
npm 426B   lib/src/Model.d.ts                                                                         
npm 1.6kB  lib/src/Model.js                                                                           
npm 409B   lib/src/Model.js.map                                                                       
npm 1.3kB  lib/src/platforms/alexa/AlexaEvent.d.ts                                                    
npm 4.7kB  lib/src/platforms/alexa/AlexaEvent.js                                                      
npm 3.0kB  lib/src/platforms/alexa/AlexaEvent.js.map                                                  
npm 238B   lib/src/platforms/alexa/AlexaIntent.d.ts                                                   
npm 1.6kB  lib/src/platforms/alexa/AlexaIntent.js                                                     
npm 541B   lib/src/platforms/alexa/AlexaIntent.js.map                                                 
npm 1.7kB  lib/src/platforms/alexa/AlexaPlatform.d.ts                                                 
npm 5.3kB  lib/src/platforms/alexa/AlexaPlatform.js                                                   
npm 2.8kB  lib/src/platforms/alexa/AlexaPlatform.js.map                                               
npm 881B   lib/src/platforms/alexa/AlexaReply.d.ts                                                    
npm 5.1kB  lib/src/platforms/alexa/AlexaReply.js                                                      
npm 3.7kB  lib/src/platforms/alexa/AlexaReply.js.map                                                  
npm 479B   lib/src/platforms/alexa/apis/ApiBase.d.ts                                                  
npm 2.5kB  lib/src/platforms/alexa/apis/ApiBase.js                                                    
npm 1.2kB  lib/src/platforms/alexa/apis/ApiBase.js.map                                                
npm 489B   lib/src/platforms/alexa/apis/AuthenticationBase.d.ts                                       
npm 2.5kB  lib/src/platforms/alexa/apis/AuthenticationBase.js                                         
npm 789B   lib/src/platforms/alexa/apis/AuthenticationBase.js.map                                     
npm 860B   lib/src/platforms/alexa/apis/CustomerContact.d.ts                                          
npm 2.9kB  lib/src/platforms/alexa/apis/CustomerContact.js                                            
npm 1.3kB  lib/src/platforms/alexa/apis/CustomerContact.js.map                                        
npm 720B   lib/src/platforms/alexa/apis/DeviceAddress.d.ts                                            
npm 2.1kB  lib/src/platforms/alexa/apis/DeviceAddress.js                                              
npm 445B   lib/src/platforms/alexa/apis/DeviceAddress.js.map                                          
npm 257B   lib/src/platforms/alexa/apis/DeviceBase.d.ts                                               
npm 1.6kB  lib/src/platforms/alexa/apis/DeviceBase.js                                                 
npm 421B   lib/src/platforms/alexa/apis/DeviceBase.js.map                                             
npm 1.3kB  lib/src/platforms/alexa/apis/DeviceSettings.d.ts                                           
npm 3.2kB  lib/src/platforms/alexa/apis/DeviceSettings.js                                             
npm 1.2kB  lib/src/platforms/alexa/apis/DeviceSettings.js.map                                         
npm 985B   lib/src/platforms/alexa/apis/index.d.ts                                                    
npm 2.9kB  lib/src/platforms/alexa/apis/index.js                                                      
npm 990B   lib/src/platforms/alexa/apis/index.js.map                                                  
npm 1.5kB  lib/src/platforms/alexa/apis/InSkillPurchase.d.ts                                          
npm 4.3kB  lib/src/platforms/alexa/apis/InSkillPurchase.js                                            
npm 2.8kB  lib/src/platforms/alexa/apis/InSkillPurchase.js.map                                        
npm 3.6kB  lib/src/platforms/alexa/apis/Lists.d.ts                                                    
npm 6.3kB  lib/src/platforms/alexa/apis/Lists.js                                                      
npm 2.9kB  lib/src/platforms/alexa/apis/Lists.js.map                                                  
npm 462B   lib/src/platforms/alexa/apis/Messaging.d.ts                                                
npm 2.3kB  lib/src/platforms/alexa/apis/Messaging.js                                                  
npm 743B   lib/src/platforms/alexa/apis/Messaging.js.map                                              
npm 702B   lib/src/platforms/alexa/apis/proactiveEventBuilders/EventBuilder.d.ts                      
npm 3.4kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/EventBuilder.js                        
npm 1.9kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/EventBuilder.js.map                    
npm 932B   lib/src/platforms/alexa/apis/proactiveEventBuilders/index.d.ts                             
npm 2.6kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/index.js                               
npm 818B   lib/src/platforms/alexa/apis/proactiveEventBuilders/index.js.map                           
npm 738B   lib/src/platforms/alexa/apis/proactiveEventBuilders/MediaContentEventBuilder.d.ts          
npm 3.0kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/MediaContentEventBuilder.js            
npm 1.2kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/MediaContentEventBuilder.js.map        
npm 727B   lib/src/platforms/alexa/apis/proactiveEventBuilders/MessageAlertEventBuilder.d.ts          
npm 2.8kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/MessageAlertEventBuilder.js            
npm 1.1kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/MessageAlertEventBuilder.js.map        
npm 839B   lib/src/platforms/alexa/apis/proactiveEventBuilders/OccasionEventBuilder.d.ts              
npm 3.2kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/OccasionEventBuilder.js                
npm 1.2kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/OccasionEventBuilder.js.map            
npm 637B   lib/src/platforms/alexa/apis/proactiveEventBuilders/OrderStatusEventBuilder.d.ts           
npm 2.6kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/OrderStatusEventBuilder.js             
npm 909B   lib/src/platforms/alexa/apis/proactiveEventBuilders/OrderStatusEventBuilder.js.map         
npm 794B   lib/src/platforms/alexa/apis/proactiveEventBuilders/SocialGameInviteEventBuilder.d.ts      
npm 3.1kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/SocialGameInviteEventBuilder.js        
npm 1.2kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/SocialGameInviteEventBuilder.js.map    
npm 504B   lib/src/platforms/alexa/apis/proactiveEventBuilders/SportsEventBuilder.d.ts                
npm 2.4kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/SportsEventBuilder.js                  
npm 1.1kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/SportsEventBuilder.js.map              
npm 1.1kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/TrashCollectionAlertEventBuilder.d.ts  
npm 3.3kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/TrashCollectionAlertEventBuilder.js    
npm 1.2kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/TrashCollectionAlertEventBuilder.js.map
npm 644B   lib/src/platforms/alexa/apis/proactiveEventBuilders/WeatherAlertEventBuilder.d.ts          
npm 2.8kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/WeatherAlertEventBuilder.js            
npm 1.1kB  lib/src/platforms/alexa/apis/proactiveEventBuilders/WeatherAlertEventBuilder.js.map        
npm 411B   lib/src/platforms/alexa/apis/ProactiveEvents.d.ts                                          
npm 2.3kB  lib/src/platforms/alexa/apis/ProactiveEvents.js                                            
npm 770B   lib/src/platforms/alexa/apis/ProactiveEvents.js.map                                        
npm 2.3kB  lib/src/platforms/alexa/apis/Reminders.d.ts                                                
npm 5.3kB  lib/src/platforms/alexa/apis/Reminders.js                                                  
npm 2.8kB  lib/src/platforms/alexa/apis/Reminders.js.map                                              
npm 6.6kB  lib/src/platforms/alexa/directives.d.ts                                                    
npm 15.7kB lib/src/platforms/alexa/directives.js                                                      
npm 11.7kB lib/src/platforms/alexa/directives.js.map                                                  
npm 1.1kB  lib/src/platforms/alexa/DisplayTemplateBuilder.d.ts                                        
npm 2.5kB  lib/src/platforms/alexa/DisplayTemplateBuilder.js                                          
npm 2.3kB  lib/src/platforms/alexa/DisplayTemplateBuilder.js.map                                      
npm 943B   lib/src/platforms/alexa/GadgetController.d.ts                                              
npm 3.0kB  lib/src/platforms/alexa/GadgetController.js                                                
npm 2.3kB  lib/src/platforms/alexa/GadgetController.js.map                                            
npm 2.5kB  lib/src/platforms/alexa/GameEngine.d.ts                                                    
npm 6.2kB  lib/src/platforms/alexa/GameEngine.js                                                      
npm 4.4kB  lib/src/platforms/alexa/GameEngine.js.map                                                  
npm 710B   lib/src/platforms/alexa/index.d.ts                                                         
npm 1.8kB  lib/src/platforms/alexa/index.js                                                           
npm 768B   lib/src/platforms/alexa/index.js.map                                                       
npm 998B   lib/src/platforms/alexa/utils.d.ts                                                         
npm 659B   lib/src/platforms/alexa/utils.js                                                           
npm 588B   lib/src/platforms/alexa/utils.js.map                                                       
npm 1.4kB  lib/src/platforms/botframework/BotFrameworkEvent.d.ts                                      
npm 5.5kB  lib/src/platforms/botframework/BotFrameworkEvent.js                                        
npm 4.4kB  lib/src/platforms/botframework/BotFrameworkEvent.js.map                                    
npm 200B   lib/src/platforms/botframework/BotFrameworkInterfaces.d.ts                                 
npm 127B   lib/src/platforms/botframework/BotFrameworkInterfaces.js                                   
npm 168B   lib/src/platforms/botframework/BotFrameworkInterfaces.js.map                               
npm 2.0kB  lib/src/platforms/botframework/BotFrameworkPlatform.d.ts                                   
npm 6.8kB  lib/src/platforms/botframework/BotFrameworkPlatform.js                                     
npm 4.5kB  lib/src/platforms/botframework/BotFrameworkPlatform.js.map                                 
npm 1.6kB  lib/src/platforms/botframework/BotFrameworkReply.d.ts                                      
npm 6.9kB  lib/src/platforms/botframework/BotFrameworkReply.js                                        
npm 5.1kB  lib/src/platforms/botframework/BotFrameworkReply.js.map                                    
npm 1.8kB  lib/src/platforms/botframework/directives.d.ts                                             
npm 3.5kB  lib/src/platforms/botframework/directives.js                                               
npm 2.9kB  lib/src/platforms/botframework/directives.js.map                                           
npm 260B   lib/src/platforms/botframework/index.d.ts                                                  
npm 734B   lib/src/platforms/botframework/index.js                                                    
npm 345B   lib/src/platforms/botframework/index.js.map                                                
npm 180B   lib/src/platforms/create-server.d.ts                                                       
npm 1.3kB  lib/src/platforms/create-server.js                                                         
npm 1.3kB  lib/src/platforms/create-server.js.map                                                     
npm 1.5kB  lib/src/platforms/dialogflow/DialogflowEvent.d.ts                                          
npm 3.5kB  lib/src/platforms/dialogflow/DialogflowEvent.js                                            
npm 1.7kB  lib/src/platforms/dialogflow/DialogflowEvent.js.map                                        
npm 316B   lib/src/platforms/dialogflow/DialogflowIntent.d.ts                                         
npm 858B   lib/src/platforms/dialogflow/DialogflowIntent.js                                           
npm 968B   lib/src/platforms/dialogflow/DialogflowIntent.js.map                                       
npm 562B   lib/src/platforms/dialogflow/DialogflowPlatform.d.ts                                       
npm 1.9kB  lib/src/platforms/dialogflow/DialogflowPlatform.js                                         
npm 504B   lib/src/platforms/dialogflow/DialogflowPlatform.js.map                                     
npm 1.5kB  lib/src/platforms/dialogflow/DialogflowReply.d.ts                                          
npm 5.5kB  lib/src/platforms/dialogflow/DialogflowReply.js                                            
npm 3.7kB  lib/src/platforms/dialogflow/DialogflowReply.js.map                                        
npm 380B   lib/src/platforms/dialogflow/DialogflowSession.d.ts                                        
npm 777B   lib/src/platforms/dialogflow/DialogflowSession.js                                          
npm 792B   lib/src/platforms/dialogflow/DialogflowSession.js.map                                      
npm 945B   lib/src/platforms/dialogflow/facebook/builders/FacebookButtonTemplateBuilder.d.ts          
npm 2.7kB  lib/src/platforms/dialogflow/facebook/builders/FacebookButtonTemplateBuilder.js            
npm 1.4kB  lib/src/platforms/dialogflow/facebook/builders/FacebookButtonTemplateBuilder.js.map        
npm 1.4kB  lib/src/platforms/dialogflow/facebook/builders/FacebookElementTemplateBuilder.d.ts         
npm 3.2kB  lib/src/platforms/dialogflow/facebook/builders/FacebookElementTemplateBuilder.js           
npm 1.7kB  lib/src/platforms/dialogflow/facebook/builders/FacebookElementTemplateBuilder.js.map       
npm 911B   lib/src/platforms/dialogflow/facebook/builders/FacebookTemplateBuilder.d.ts                
npm 2.5kB  lib/src/platforms/dialogflow/facebook/builders/FacebookTemplateBuilder.js                  
npm 1.3kB  lib/src/platforms/dialogflow/facebook/builders/FacebookTemplateBuilder.js.map              
npm 233B   lib/src/platforms/dialogflow/facebook/builders/index.d.ts                                  
npm 640B   lib/src/platforms/dialogflow/facebook/builders/index.js                                    
npm 267B   lib/src/platforms/dialogflow/facebook/builders/index.js.map                                
npm 4.2kB  lib/src/platforms/dialogflow/facebook/directives.d.ts                                      
npm 12.6kB lib/src/platforms/dialogflow/facebook/directives.js                                        
npm 8.3kB  lib/src/platforms/dialogflow/facebook/directives.js.map                                    
npm 2.1kB  lib/src/platforms/dialogflow/facebook/FacebookEvent.d.ts                                   
npm 6.6kB  lib/src/platforms/dialogflow/facebook/FacebookEvent.js                                     
npm 4.1kB  lib/src/platforms/dialogflow/facebook/FacebookEvent.js.map                                 
npm 716B   lib/src/platforms/dialogflow/facebook/FacebookPlatform.d.ts                                
npm 2.5kB  lib/src/platforms/dialogflow/facebook/FacebookPlatform.js                                  
npm 669B   lib/src/platforms/dialogflow/facebook/FacebookPlatform.js.map                              
npm 911B   lib/src/platforms/dialogflow/facebook/FacebookReply.d.ts                                   
npm 3.6kB  lib/src/platforms/dialogflow/facebook/FacebookReply.js                                     
npm 2.0kB  lib/src/platforms/dialogflow/facebook/FacebookReply.js.map                                 
npm 2.6kB  lib/src/platforms/dialogflow/google/directives.d.ts                                        
npm 6.8kB  lib/src/platforms/dialogflow/google/directives.js                                          
npm 5.1kB  lib/src/platforms/dialogflow/google/directives.js.map                                      
npm 1.0kB  lib/src/platforms/dialogflow/google/GoogleAssistantEvent.d.ts                              
npm 3.3kB  lib/src/platforms/dialogflow/google/GoogleAssistantEvent.js                                
npm 1.6kB  lib/src/platforms/dialogflow/google/GoogleAssistantEvent.js.map                            
npm 1.0kB  lib/src/platforms/dialogflow/google/GoogleAssistantPlatform.d.ts                           
npm 3.3kB  lib/src/platforms/dialogflow/google/GoogleAssistantPlatform.js                             
npm 1.3kB  lib/src/platforms/dialogflow/google/GoogleAssistantPlatform.js.map                         
npm 1.6kB  lib/src/platforms/dialogflow/index.d.ts                                                    
npm 3.7kB  lib/src/platforms/dialogflow/index.js                                                      
npm 1.4kB  lib/src/platforms/dialogflow/index.js.map                                                  
npm 47B    lib/src/platforms/index.d.ts                                                               
npm 210B   lib/src/platforms/index.js                                                                 
npm 153B   lib/src/platforms/index.js.map                                                             
npm 2.1kB  lib/src/platforms/VoxaPlatform.d.ts                                                        
npm 5.8kB  lib/src/platforms/VoxaPlatform.js                                                          
npm 4.0kB  lib/src/platforms/VoxaPlatform.js.map                                                      
npm 107B   lib/src/plugins/auto-load.d.ts                                                             
npm 2.0kB  lib/src/plugins/auto-load.js                                                               
npm 919B   lib/src/plugins/auto-load.js.map                                                           
npm 156B   lib/src/plugins/index.d.ts                                                                 
npm 383B   lib/src/plugins/index.js                                                                   
npm 222B   lib/src/plugins/index.js.map                                                               
npm 106B   lib/src/plugins/replace-intent.d.ts                                                        
npm 1.8kB  lib/src/plugins/replace-intent.js                                                          
npm 656B   lib/src/plugins/replace-intent.js.map                                                      
npm 94B    lib/src/plugins/state-flow.d.ts                                                            
npm 698B   lib/src/plugins/state-flow.js                                                              
npm 743B   lib/src/plugins/state-flow.js.map                                                          
npm 1.4kB  lib/src/renderers/Renderer.d.ts                                                            
npm 5.1kB  lib/src/renderers/Renderer.js                                                              
npm 3.5kB  lib/src/renderers/Renderer.js.map                                                          
npm 177B   lib/src/StateMachine/index.d.ts                                                            
npm 380B   lib/src/StateMachine/index.js                                                              
npm 228B   lib/src/StateMachine/index.js.map                                                          
npm 560B   lib/src/StateMachine/State.d.ts                                                            
npm 2.0kB  lib/src/StateMachine/State.js                                                              
npm 851B   lib/src/StateMachine/State.js.map                                                          
npm 1.3kB  lib/src/StateMachine/StateMachine.d.ts                                                     
npm 6.5kB  lib/src/StateMachine/StateMachine.js                                                       
npm 4.4kB  lib/src/StateMachine/StateMachine.js.map                                                   
npm 709B   lib/src/StateMachine/transitions.d.ts                                                      
npm 2.1kB  lib/src/StateMachine/transitions.js                                                        
npm 679B   lib/src/StateMachine/transitions.js.map                                                    
npm 2.5kB  lib/src/VoxaApp.d.ts                                                                       
npm 16.9kB lib/src/VoxaApp.js                                                                         
npm 12.9kB lib/src/VoxaApp.js.map                                                                     
npm 2.5kB  lib/src/VoxaEvent.d.ts                                                                     
npm 2.5kB  lib/src/VoxaEvent.js                                                                       
npm 1.2kB  lib/src/VoxaEvent.js.map                                                                   
npm 1.4kB  lib/src/VoxaReply.d.ts                                                                     
npm 2.1kB  lib/src/VoxaReply.js                                                                       
npm 883B   lib/src/VoxaReply.js.map                                                                   
npm 2.0kB  src/azure.ts                                                                               
npm 5.3kB  src/directives.ts                                                                          
npm 1.7kB  src/errors/handler.ts                                                                      
npm 1.9kB  src/errors/index.ts                                                                        
npm 51B    src/errors/NotImplementedError.ts                                                          
npm 1.6kB  src/errors/OnSessionEndedError.ts                                                          
npm 1.3kB  src/errors/SSMLError.ts                                                                    
npm 44B    src/errors/TimeoutError.ts                                                                 
npm 3.2kB  src/index.ts                                                                               
npm 1.9kB  src/lambda.ts                                                                              
npm 1.7kB  src/Model.ts                                                                               
npm 5.3kB  src/platforms/alexa/AlexaEvent.ts                                                          
npm 1.7kB  src/platforms/alexa/AlexaIntent.ts                                                         
npm 5.7kB  src/platforms/alexa/AlexaPlatform.ts                                                       
npm 4.9kB  src/platforms/alexa/AlexaReply.ts                                                          
npm 2.6kB  src/platforms/alexa/apis/ApiBase.ts                                                        
npm 2.2kB  src/platforms/alexa/apis/AuthenticationBase.ts                                             
npm 2.9kB  src/platforms/alexa/apis/CustomerContact.ts                                                
npm 2.1kB  src/platforms/alexa/apis/DeviceAddress.ts                                                  
npm 1.6kB  src/platforms/alexa/apis/DeviceBase.ts                                                     
npm 3.2kB  src/platforms/alexa/apis/DeviceSettings.ts                                                 
npm 1.0kB  src/platforms/alexa/apis/index.ts                                                          
npm 5.2kB  src/platforms/alexa/apis/InSkillPurchase.ts                                                
npm 7.0kB  src/platforms/alexa/apis/Lists.ts                                                          
npm 2.3kB  src/platforms/alexa/apis/Messaging.ts                                                      
npm 3.3kB  src/platforms/alexa/apis/proactiveEventBuilders/EventBuilder.ts                            
npm 966B   src/platforms/alexa/apis/proactiveEventBuilders/index.ts                                   
npm 2.4kB  src/platforms/alexa/apis/proactiveEventBuilders/MediaContentEventBuilder.ts                
npm 2.2kB  src/platforms/alexa/apis/proactiveEventBuilders/MessageAlertEventBuilder.ts                
npm 2.5kB  src/platforms/alexa/apis/proactiveEventBuilders/OccasionEventBuilder.ts                    
npm 2.2kB  src/platforms/alexa/apis/proactiveEventBuilders/OrderStatusEventBuilder.ts                 
npm 2.4kB  src/platforms/alexa/apis/proactiveEventBuilders/SocialGameInviteEventBuilder.ts            
npm 2.4kB  src/platforms/alexa/apis/proactiveEventBuilders/SportsEventBuilder.ts                      
npm 2.4kB  src/platforms/alexa/apis/proactiveEventBuilders/TrashCollectionAlertEventBuilder.ts        
npm 2.4kB  src/platforms/alexa/apis/proactiveEventBuilders/WeatherAlertEventBuilder.ts                
npm 2.2kB  src/platforms/alexa/apis/ProactiveEvents.ts                                                
npm 5.5kB  src/platforms/alexa/apis/Reminders.ts                                                      
npm 17.4kB src/platforms/alexa/directives.ts                                                          
npm 3.2kB  src/platforms/alexa/DisplayTemplateBuilder.ts                                              
npm 2.9kB  src/platforms/alexa/GadgetController.ts                                                    
npm 6.6kB  src/platforms/alexa/GameEngine.ts                                                          
npm 740B   src/platforms/alexa/index.ts                                                               
npm 1.4kB  src/platforms/alexa/utils.ts                                                               
npm 5.5kB  src/platforms/botframework/BotFrameworkEvent.ts                                            
npm 191B   src/platforms/botframework/BotFrameworkInterfaces.ts                                       
npm 7.4kB  src/platforms/botframework/BotFrameworkPlatform.ts                                         
npm 7.6kB  src/platforms/botframework/BotFrameworkReply.ts                                            
npm 4.4kB  src/platforms/botframework/directives.ts                                                   
npm 268B   src/platforms/botframework/index.ts                                                        
npm 1.0kB  src/platforms/create-server.ts                                                             
npm 3.9kB  src/platforms/dialogflow/DialogflowEvent.ts                                                
npm 899B   src/platforms/dialogflow/DialogflowIntent.ts                                               
npm 2.0kB  src/platforms/dialogflow/DialogflowPlatform.ts                                             
npm 6.0kB  src/platforms/dialogflow/DialogflowReply.ts                                                
npm 936B   src/platforms/dialogflow/DialogflowSession.ts                                              
npm 3.1kB  src/platforms/dialogflow/facebook/builders/FacebookButtonTemplateBuilder.ts                
npm 3.9kB  src/platforms/dialogflow/facebook/builders/FacebookElementTemplateBuilder.ts               
npm 3.0kB  src/platforms/dialogflow/facebook/builders/FacebookTemplateBuilder.ts                      
npm 233B   src/platforms/dialogflow/facebook/builders/index.ts                                        
npm 12.9kB src/platforms/dialogflow/facebook/directives.ts                                            
npm 6.1kB  src/platforms/dialogflow/facebook/FacebookEvent.ts                                         
npm 2.9kB  src/platforms/dialogflow/facebook/FacebookPlatform.ts                                      
npm 3.7kB  src/platforms/dialogflow/facebook/FacebookReply.ts                                         
npm 9.7kB  src/platforms/dialogflow/google/directives.ts                                              
npm 3.7kB  src/platforms/dialogflow/google/GoogleAssistantEvent.ts                                    
npm 3.6kB  src/platforms/dialogflow/google/GoogleAssistantPlatform.ts                                 
npm 1.7kB  src/platforms/dialogflow/index.ts                                                          
npm 47B    src/platforms/index.ts                                                                     
npm 6.7kB  src/platforms/VoxaPlatform.ts                                                              
npm 2.0kB  src/plugins/auto-load.ts                                                                   
npm 157B   src/plugins/index.ts                                                                       
npm 1.7kB  src/plugins/replace-intent.ts                                                              
npm 765B   src/plugins/state-flow.ts                                                                  
npm 5.4kB  src/renderers/Renderer.ts                                                                  
npm 177B   src/StateMachine/index.ts                                                                  
npm 2.2kB  src/StateMachine/State.ts                                                                  
npm 7.5kB  src/StateMachine/StateMachine.ts                                                           
npm 2.2kB  src/StateMachine/transitions.ts                                                            
npm 18.3kB src/VoxaApp.ts                                                                             
npm 4.8kB  src/VoxaEvent.ts                                                                           
npm 3.1kB  src/VoxaReply.ts                                                                           
npm === Tarball Details === 
npm name:          voxa                                    
npm version:       3.1.0-alpha8                            
npm package size:  182.2 kB                                
npm unpacked size: 892.4 kB                                
npm shasum:        bd5f6ae3e664735832d43fd99e5c6cd0ad09c586
npm integrity:     sha512-Vm9/HU8G3rskj[...]buvtQ8uElhfWg==
npm total files:   336                                     
npm 
+ voxa@3.1.0-alpha8
