### ISSUE TITLE
Directive method requires three parameters when only needs one

### ISSUE THREAD

**Issue by wuelcas** [VoxaAI/voxa#247]
Every directive has a `writeToReply` method that requires three parameters: `reply`, `event` and `transition`. Those three params are not used in all directives, most of the directives just use the first one.

When building a skill in vanilla Javascript you can just pass the one you need to pass, but when using Typescript you are obligated to pass the three params.

One practical example for using the `writeToReply` method inside a skill, is when writing the PlayAudio directive in a reply on a `AudioPlayer.PlaybackNearlyFinished` request. That directive just need the `reply` param, the other two params are not used at all.

```
voxaApp['onAudioPlayer.PlaybackNearlyFinished']((voxaEvent: IVoxaEvent, reply: AlexaReply) => {
  const playAudio = new PlayAudio({
    behavior: "REPLACE_ALL",
    offsetInMilliseconds: 0,
    token: "",
    url: 'https://domain.com/audio.mp3'
  });

  // If I pass only the reply param, Typescript will complain
  playAudio.writeToReply(reply, voxaEvent, {});

  return reply;
});
```

**Comment by rmberrios** [comment]
Agreed!
