### ISSUE TITLE
Support for Dynamic Entities?

### ISSUE THREAD

**Issue by patcat** [VoxaAI/voxa#253]
Hi team!

Has anyone explored using Alexa's dynamic entities within Voxa? I've been trying to get this to work, but Voxa doesn't seem to use my dynamic entities — despite them existing within directives throughout my use of the skill.

I've got a directive that has `updateBehaviour` set to `"REPLACE"` and a list of dynamic entity values as per [these docs](https://developer.amazon.com/docs/custom-skills/display-interface-reference.html). I've managed to get it to work in a Node app without using Voxa, but Voxa doesn't seem to pick up the dynamic entities.

The custom directive concept I've been trying is summarised like so (I've got it broken up a bit more into a reusable directive that doesn't have the behavior and types hardcoded in below):

```
'use strict';

class DynamicEntityDirective {
  constructor(updateBehavior, types) {
    this.updateBehavior = updateBehavior;
    this.types = types;
  }

  async writeToReply(reply) {
    const response = reply.response;
    if (!response.directives) {
      response.directives = [];
    }

    reply.response.directives.push({
      type: 'Dialog.UpdateDynamicEntities',
      updateBehavior: 'REPLACE',
      types: [
        {
          name: 'dynamic-list',
          values: [
            {
              id: '1',
              name: {
                value: 'Dynamic Item 1',
                synonyms: ['Item 1', 'Item One']
              }
            },
            {
              id: '2',
              name: {
                value: 'Dynamic Item 2',
                synonyms: ['Item 2', 'Item Two']
              }
            },
            {
              id: '3',
              name: {
                value: 'Dynamic Item 3',
                synonyms: ['Item 3', 'Item Three']
              }
            }
          ]
        }
      ]
    });
  }
}

DynamicEntityDirective.key = 'alexaDynamicEntity';
DynamicEntityDirective.platform = 'alexa';

module.exports = DynamicEntityDirective;
```

Referred to in responses to initial launch intents like so:

```
return {
          directives: [buildDynamicEntityDirectives(voxaEvent)],
          reply: 'SampleResponse',
          to: 'entry',
          flow: 'yield',
};
```

Any ideas? Thanks for your help!

**Comment by wuelcas** [comment]
I think maybe something's wrong inside the `buildDynamicEntityDirectives` function. Can you share the code block of that function?

Also, you can skip that function and just use the directive class you created like this:

```
const updateBehavior = "REPLACE";
const types = [{ ... }];
const dynamicEntity = new DynamicEntityDirective(updateBehavior, types);

return {
  directives: [dynamicEntity],
  reply: 'SampleResponse',
  to: 'entry',
  flow: 'yield',
};
```

**Comment by patcat** [comment]
Ah yes, sorry that was just me missing something when trying to simplify sending this over as an issue, my `buildDynamicEntityDirectives` function isn't doing anything in particular at the moment, just returning the `DynamicEntityDirective`:

```
buildDynamicEntityDirectives: (voxaEvent) => {
    const dynamicEntityDirective = new DynamicEntityDirective(
      'REPLACE',
      [
        {
          name: 'dynamic-list',
          values: [
            {
              id: '1',
              name: {
                value: 'Dynamic Item 1',
                synonyms: ['Item 1', 'Item One']
              }
            },
            {
              id: '2',
              name: {
                value: 'Dynamic Item 2',
                synonyms: ['Item 2', 'Item Two']
              }
            },
            {
              id: '3',
              name: {
                value: 'Dynamic Item 3',
                synonyms: ['Item 3', 'Item Three']
              }
            }
          ]
        }
      ]
    );

    return dynamicEntityDirective;
}
```

So it's already pretty much returning the dynamic entity itself. Has anyone gotten dynamic entities to work within Voxa before? Is there anything else that could be preventing it from working?

I do see the directive coming through when I test within the Alexa Developer Console — it shows up in the JSON Output. It's just the dynamic entities never seem to actually work afterwards, they don't get picked up when phrases have the dynamic entities within them. It acts as if I hadn't set up dynamic entities at all. Could Voxa be clearing it in between requests or something along those lines?

Thank you for your help!

**Comment by omenocal** [comment]
@patcat I've started playing with them, and the only case where it's not working for me is with numbers. If I have for example as part of my entities:
25
25 apples

And I say: `twenty five` or write `twenty five` in the test console, it will never pick it up. So, I've decided to go with letters instead of numbers. That's working really well so far.

**Comment by patcat** [comment]
That's so strange! For me it just doesn't ever pick up my dynamic entities... I'm trying company names as my test (e.g. BMW, Starbucks, Walmart) but get FALLBACK_INTENT whenever I try to use just the company name that's one of my dynamic entities, or I get my dynamic entity's intent if I have it as part of a sentence to make it easier to tell which intent it wants, but only the existing entities, not the dynamic ones, ever get picked up within it.

Would it be possible for you to share the sample that you've got working so I can see whether I'm missing something obvious @omenocal ?

Thank you for taking the time to help out so far, it's much appreciated!

**Comment by omenocal** [comment]
Hey @patcat unfortunately I can't as it's part of a private project, but let's see what I got so far in the requests and response:

In my request I send a directive with possible slot values and synonyms. If you have gotten this in your response, then it's not a Voxa issue as you're sending it correctly:
![image](https://user-images.githubusercontent.com/12286824/62797837-ef5b2000-ba99-11e9-9198-6591a4b3f30a.png)

When I send the command to Alexa with one of the synonyms, I get this:
![image](https://user-images.githubusercontent.com/12286824/62797876-10bc0c00-ba9a-11e9-903b-abc63ceab6cc.png)

This means, my dynamic entity was picked up correctly and I always look for the dynamic value ID which is A, I don't care too much about what the user said but the ID of that answer. So it's picking it up correctly.

Now, my `AnswerOnlyIntent` intent has the utterance `{gameAnswer}` which is the one I use to capture the answer from the user. Maybe you need to look at the utterances of the slot you're updating and see if they cover the command the user is saying that contains your dynamic entity.

**Comment by patcat** [comment]
Thanks for that — I've managed to get it to work too. The one thing that worked most reliably was setting the entity as required for slot filling in the console — which seemed to ensure that the Amazon side of things picked it up correctly alongside some other changes in how I set up my code to keep track of those entities. Seems to be working to a much better extent! Thank you for your help :)
