### ISSUE TITLE
Add directive for dynamic entities

### ISSUE THREAD

**Issue by wuelcas** [VoxaAI/voxa#262]
We need to create a built-in directive for Dynamic Entities

**Comment by spatical** [comment]
Would it make sense to create a directive that works for both Dynamic Entities and DialogFlow Session Entities in one directive?   I haven't actually used or tested the session entities before, so I'm not sure how different they are compared to Alexa's.  So it might not be good 1 to 1 parity in the features.   But it should at least be considered.

**Comment by armonge** [comment]
This was fixed by https://github.com/VoxaAI/voxa/pull/264

@spatical you can open a new issue and PR for something like that
